In [1]:
using LinearAlgebra

In [4]:
vec_list = [normalize!(randn(6)) for j=1:4]


4-element Vector{Vector{Float64}}:
 [0.37883268169182394, 0.45916046428959695, 0.33180777202964445, 0.6806612235142964, -0.1650289262247398, -0.21219524511495805]
 [-0.2935795789633731, -0.08386199559223018, 0.20572809444195458, 0.8961875343613418, 0.17800160085130265, 0.1720973010188473]
 [-0.4446410737575766, 0.3552153895079222, 0.32154402150243866, 0.5611802758554121, 0.39396953712961513, -0.3202974970635955]
 [0.21114583018874325, -0.1953671323409361, -0.7110864111174259, -0.49169131556724677, -0.15251850020673613, 0.38286158753440197]

In [5]:

mat = ones((4,4))-Matrix(I,(4,4))

4×4 Matrix{Float64}:
 0.0  1.0  1.0  1.0
 1.0  0.0  1.0  1.0
 1.0  1.0  0.0  1.0
 1.0  1.0  1.0  0.0

In [6]:
println(cond(mat))

3.0000000000000004


In [16]:
for m=2:20

    mat = -ones((m,m))+Matrix(I,(m,m))
    
    #println(cond(mat))
    
    F = eigen(mat)
    
    display(F.values)
    
    display(F.vectors)
end

2-element Vector{Float64}:
 -1.0
  1.0

2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

3-element Vector{Float64}:
 -1.9999999999999982
  0.9999999999999999
  1.0000000000000002

3×3 Matrix{Float64}:
 -0.57735   0.707107  -0.408248
 -0.57735  -0.707107  -0.408248
 -0.57735   0.0        0.816497

4-element Vector{Float64}:
 -2.9999999999999982
  0.9999999999999996
  1.0
  1.0

4×4 Matrix{Float64}:
 0.5  -0.408248   0.707107  -0.288675
 0.5  -0.408248  -0.707107  -0.288675
 0.5   0.816497   0.0       -0.288675
 0.5   0.0        0.0        0.866025

5-element Vector{Float64}:
 -3.999999999999998
  1.0
  1.0
  1.0
  1.0

5×5 Matrix{Float64}:
 -0.447214  -0.211325  -0.288675   0.788675     -0.223607
 -0.447214   0.788675  -0.288675  -0.211325     -0.223607
 -0.447214  -0.57735   -0.288675  -0.57735      -0.223607
 -0.447214   0.0        0.866025  -4.16334e-17  -0.223607
 -0.447214   0.0        0.0        0.0           0.894427

6-element Vector{Float64}:
 -4.9999999999999964
  0.9999999999999993
  0.9999999999999998
  1.0000000000000004
  1.0000000000000009
  1.0000000000000009

6×6 Matrix{Float64}:
 -0.408248  -0.408248    0.707107     -0.182574  -0.288675     -0.223607
 -0.408248  -0.408248   -0.707107     -0.182574  -0.288675     -0.223607
 -0.408248   0.816497   -2.22513e-16  -0.182574  -0.288675     -0.223607
 -0.408248  -1.249e-16   9.56794e-17  -0.182574   0.866025     -0.223607
 -0.408248   0.0         4.01682e-17  -0.182574  -1.60673e-16   0.894427
 -0.408248   0.0         0.0           0.912871   0.0           0.0

7-element Vector{Float64}:
 -5.999999999999999
  0.9999999999999997
  0.9999999999999999
  0.9999999999999999
  1.0000000000000002
  1.0000000000000002
  1.0000000000000007

7×7 Matrix{Float64}:
 -0.377964  -0.154303  -0.223607      0.707107     …  -0.408248     -0.182574
 -0.377964  -0.154303  -0.223607     -0.707107        -0.408248     -0.182574
 -0.377964  -0.154303  -0.223607      8.75605e-17      0.816497     -0.182574
 -0.377964  -0.154303  -0.223607      0.0             -2.24975e-16  -0.182574
 -0.377964  -0.154303   0.894427      0.0              8.03365e-17  -0.182574
 -0.377964  -0.154303   1.56347e-16   0.0          …   0.0           0.912871
 -0.377964   0.92582    0.0           0.0              0.0           0.0

8-element Vector{Float64}:
 -6.999999999999999
  0.9999999999999999
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0

8×8 Matrix{Float64}:
 -0.353553  -0.133631  -0.11835      …   0.88165      -0.11835
 -0.353553  -0.133631  -0.11835         -0.11835       0.88165
 -0.353553  -0.133631   0.88165         -0.11835      -0.11835
 -0.353553  -0.133631  -0.11835         -0.11835      -0.11835
 -0.353553  -0.133631  -0.11835         -0.11835      -0.11835
 -0.353553  -0.133631  -0.408248     …  -0.408248     -0.408248
 -0.353553  -0.133631   3.82462e-17      3.82462e-17   1.91231e-17
 -0.353553   0.935414   0.0              0.0           0.0

9-element Vector{Float64}:
 -7.999999999999997
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0000000000000002

9×9 Matrix{Float64}:
 -0.333333  -0.103673  -0.103673     …  -0.133631   0.896327     -0.117851
 -0.333333   0.896327  -0.103673        -0.133631  -0.103673     -0.117851
 -0.333333  -0.103673   0.896327        -0.133631  -0.103673     -0.117851
 -0.333333  -0.103673  -0.103673        -0.133631  -0.103673     -0.117851
 -0.333333  -0.103673  -0.103673        -0.133631  -0.103673     -0.117851
 -0.333333  -0.103673  -0.103673     …  -0.133631  -0.103673     -0.117851
 -0.333333  -0.377964  -0.377964        -0.133631  -0.377964     -0.117851
 -0.333333   0.0        1.87843e-17      0.935414   1.87843e-17  -0.117851
 -0.333333   0.0        0.0              0.0        0.0           0.942809

10-element Vector{Float64}:
 -8.999999999999996
  0.9999999999999996
  0.9999999999999996
  0.9999999999999996
  0.9999999999999996
  1.0
  1.0
  1.0
  1.0
  1.0000000000000002

10×10 Matrix{Float64}:
 -0.316228  -0.223607     -0.182574     …   0.707107     -0.105409
 -0.316228  -0.223607     -0.182574        -0.707107     -0.105409
 -0.316228  -0.223607     -0.182574        -8.75605e-17  -0.105409
 -0.316228  -0.223607     -0.182574         0.0          -0.105409
 -0.316228   0.894427     -0.182574         0.0          -0.105409
 -0.316228   1.71125e-16   0.912871     …   0.0          -0.105409
 -0.316228   2.86556e-17  -2.66601e-16      0.0          -0.105409
 -0.316228   2.34103e-17   5.66336e-17      0.0          -0.105409
 -0.316228   1.85037e-17  -7.40149e-17      0.0          -0.105409
 -0.316228   0.0           0.0              0.0           0.948683

11-element Vector{Float64}:
 -9.999999999999996
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0
  1.0000000000000002

11×11 Matrix{Float64}:
 -0.301511  -0.0833333  -0.0833333  …  -0.105409   0.916667   -0.0953463
 -0.301511   0.916667   -0.0833333     -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333   0.916667      -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333  -0.0833333     -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333  -0.0833333     -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333  -0.0833333  …  -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333  -0.0833333     -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.0833333  -0.0833333     -0.105409  -0.0833333  -0.0953463
 -0.301511  -0.333333   -0.333333      -0.105409  -0.333333   -0.0953463
 -0.301511   0.0         0.0            0.948683   0.0        -0.0953463
 -0.301511   0.0         0.0        …   0.0        0.0         0.953463

12-element Vector{Float64}:
 -10.999999999999995
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   1.0
   1.0
   1.0
   1.0
   1.0
   1.0000000000000007
   1.0000000000000009

12×12 Matrix{Float64}:
 -0.288675  -0.182574     -0.178927     …  -0.0870388  -0.288675
 -0.288675  -0.182574     -0.178927        -0.0870388  -0.288675
 -0.288675  -0.182574     -0.178927        -0.0870388  -0.288675
 -0.288675  -0.182574     -0.178927        -0.0870388   0.866025
 -0.288675  -0.182574     -0.178927        -0.0870388  -1.18559e-16
 -0.288675   0.912871     -0.178927     …  -0.0870388  -2.58101e-17
 -0.288675  -8.46439e-17   0.0921051       -0.0870388   5.22839e-17
 -0.288675  -7.5607e-17    0.0921051       -0.0870388  -9.25186e-18
 -0.288675   7.40149e-17   0.889351        -0.0870388  -3.70074e-17
 -0.288675   0.0           7.30653e-17     -0.0870388   0.0
 -0.288675   0.0           0.0          …  -0.0870388   0.0
 -0.288675   0.0           0.0              0.957427    0.0

13-element Vector{Float64}:
 -11.999999999999998
   0.9999999999999987
   0.9999999999999991
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999998
   1.0
   1.0
   1.0
   1.0000000000000009

13×13 Matrix{Float64}:
 -0.27735  -0.131119     -0.190252     …  -0.155325     -0.288675
 -0.27735  -0.131119     -0.190252        -0.155325     -0.288675
 -0.27735  -0.131119     -0.190252        -0.155325     -0.288675
 -0.27735  -0.131119     -0.190252        -0.155325      0.866025
 -0.27735  -0.0607172    -0.190252        -0.254142      6.42294e-17
 -0.27735  -0.0607172    -0.190252     …   0.891842      2.33231e-17
 -0.27735  -0.0269959     0.0902155       -0.133037     -5.30283e-20
 -0.27735  -0.0269959     0.0902155        0.154521      2.77025e-17
 -0.27735   0.93196       0.0902155       -0.0437761     5.33406e-17
 -0.27735  -0.232059      0.870866         0.00589204   -3.65327e-17
 -0.27735   5.62237e-17  -1.80621e-17  …   3.61242e-17   0.0
 -0.27735  -7.15358e-17   0.0              0.0           0.0
 -0.27735   0.0           0.0              0.0           0.0

14-element Vector{Float64}:
 -13.0
   0.9999999999999991
   0.9999999999999991
   0.9999999999999992
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999998
   1.0
   1.0
   1.0
   1.0
   1.0000000000000004
   1.0000000000000009

14×14 Matrix{Float64}:
 -0.267261   0.0172663  -0.0626505    …   0.0186146    -0.288675
 -0.267261   0.0172663  -0.0626505        0.0186146    -0.288675
 -0.267261   0.0172663  -0.0626505        0.0186146    -0.288675
 -0.267261   0.0172663  -0.0626505        0.0186146     0.866025
 -0.267261   0.0172663  -0.0626505        0.0186146     3.5263e-16
 -0.267261   0.0172663  -0.0626505    …   0.0186146     3.12842e-17
 -0.267261  -0.157332    0.00729441       0.840682      5.17781e-17
 -0.267261  -0.157332    0.00729441      -0.112981     -3.502e-17
 -0.267261   0.853117    0.00729441      -0.147204     -6.75098e-18
 -0.267261  -0.406996   -0.498869        -0.438776     -4.83843e-17
 -0.267261  -0.235054    0.852889     …  -0.253408      8.01234e-18
 -0.267261   0.0         3.57679e-17     -2.1733e-17    3.57679e-17
 -0.267261   0.0         0.0             -1.77268e-17   0.0
 -0.267261   0.0         0.0              0.0           0.0

15-element Vector{Float64}:
 -13.999999999999991
   0.9999999999999998
   0.9999999999999998
   1.0
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000007
   1.0000000000000007
   1.0000000000000007
   1.0000000000000029

15×15 Matrix{Float64}:
 -0.258199  -0.123436   -0.0525265    -0.0690066  …  -0.223607      0.10539
 -0.258199  -0.123436   -0.0525265    -0.0690066     -0.223607      0.10539
 -0.258199  -0.123436   -0.0525265    -0.0690066     -0.223607      0.10539
 -0.258199  -0.123436   -0.0525265    -0.0690066     -0.223607      0.10539
 -0.258199  -0.123436   -0.0525265    -0.0690066      0.894427      0.10539
 -0.258199   0.110937   -0.0525265    -0.0690066  …   2.91659e-17   0.10539
 -0.258199  -0.430927   -0.229864     -0.0690066     -2.87911e-17   0.10539
 -0.258199   0.822854   -0.229864     -0.0690066      8.62458e-17   0.10539
 -0.258199   0.160339   -0.0525265    -0.0690066      4.41664e-17   0.10539
 -0.258199   0.0166765  -0.0525265    -0.0690066      3.72879e-17   0.10539
 -0.258199  -0.133262   -0.0525265    -0.0690066  …  -1.04876e-16   0.10539
 -0.258199   0.0705624   0.932467     -0.0690066      1.4035e-17    0.10539
 -0.258199   0.0        -6.34892e-17  -0.0690066      1.77268e-17

16-element Vector{Float64}:
 -14.999999999999998
   0.9999999999999986
   0.9999999999999994
   0.9999999999999994
   0.9999999999999994
   0.9999999999999994
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   1.0000000000000002
   1.0000000000000002
   1.000000000000001

16×16 Matrix{Float64}:
 -0.25  -0.167335  -0.00425399  …  -0.00188311  -0.0645497  -0.0532705
 -0.25  -0.167335  -0.00425399     -0.00188311  -0.0645497  -0.0532705
 -0.25  -0.167335  -0.00425399     -0.00188311  -0.0645497  -0.0532705
 -0.25  -0.167335  -0.00425399     -0.00188311  -0.0645497  -0.0532705
 -0.25   0.245234   0.0123873      -0.00256381  -0.0645497   0.331185
 -0.25   0.245234   0.0123873   …  -0.00256381  -0.0645497   0.331185
 -0.25   0.245234  -0.445674       -0.554671    -0.0645497   0.340293
 -0.25   0.245234   0.383123        0.590964    -0.0645497   0.340293
 -0.25  -0.167335  -0.0318287       0.0274894   -0.0645497  -0.120855
 -0.25  -0.167335  -0.00113498     -0.0058707   -0.0645497  -0.120855
 -0.25  -0.167335   0.525703    …  -0.370503    -0.0645497  -0.199
 -0.25  -0.167335  -0.595914        0.440219    -0.0645497  -0.199
 -0.25  -0.167335   0.146126       -0.104748    -0.0645497   0.045083
 -0.25  -0.167335  -0.00628634      0.00473538  -0.0645497   0.109202

17-element Vector{Float64}:
 -16.0
   0.9999999999999994
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   1.0
   1.0
   1.0
   1.0
   1.0
   1.0
   1.0
   1.0000000000000004
   1.0000000000000004

17×17 Matrix{Float64}:
 -0.242536  -0.0606339   0.00647436   …  -0.0690066    -0.0645497
 -0.242536  -0.0606339   0.00647436      -0.0690066    -0.0645497
 -0.242536  -0.0606339   0.00647436      -0.0690066    -0.0645497
 -0.242536  -0.0606339   0.00647436      -0.0690066    -0.0645497
 -0.242536  -0.0606339   0.745839        -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.655946     …  -0.0690066    -0.0645497
 -0.242536  -0.0606339   0.0596415       -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.0502833       -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.0814368       -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.0132791       -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.00799905   …  -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.000266114     -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.00446555      -0.0690066    -0.0645497
 -0.242536  -0.0606339  -0.0177024       -0.0690066    -0.0645497
 -0.242536  -0.0606339  -6.29052e-17      0.966092   

18-element Vector{Float64}:
 -16.999999999999996
   0.9999999999999993
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   1.0
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000007
   1.0000000000000007
   1.0000000000000007
   1.000000000000001
   1.0000000000000047

18×18 Matrix{Float64}:
 -0.235702  -0.112623      0.136517     …  -0.0383482    -0.0606339
 -0.235702  -0.112623      0.136517        -0.0383482    -0.0606339
 -0.235702  -0.112623      0.136517        -0.0383482    -0.0606339
 -0.235702  -0.112623      0.136517        -0.0383482    -0.0606339
 -0.235702  -0.68987      -0.274923        -0.115045     -0.0606339
 -0.235702   0.401031      0.625041     …  -0.115045     -0.0606339
 -0.235702  -0.32535       0.394376        -0.115045     -0.0606339
 -0.235702   0.142446     -0.172667        -0.115045     -0.0606339
 -0.235702   0.2323       -0.281585        -0.0383482    -0.0606339
 -0.235702   0.129681     -0.157194        -0.0383482    -0.0606339
 -0.235702   0.240574     -0.291614     …  -0.0383482    -0.0606339
 -0.235702   0.0221793    -0.0268849       -0.0383482    -0.0606339
 -0.235702   0.118257     -0.143347        -0.0383482    -0.0606339
 -0.235702   0.204644     -0.248061        -0.0383482    -0.0606339
 -0.235702   0.0101089   

19-element Vector{Float64}:
 -17.999999999999996
   0.9999999999999994
   0.9999999999999994
   0.9999999999999994
   0.9999999999999996
   0.9999999999999996
   0.9999999999999996
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   0.9999999999999999
   1.0
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000029

19×19 Matrix{Float64}:
 -0.229416  -0.123006     0.242607   …  -0.0360457   -0.0540738  -0.129677
 -0.229416  -0.123006     0.242607      -0.0360457   -0.0540738  -0.129677
 -0.229416  -0.123006     0.242607      -0.0360457   -0.0540738  -0.129677
 -0.229416  -0.123006     0.242607      -0.0360457   -0.0540738  -0.129677
 -0.229416   0.184709     0.0257288     -0.0898137   -0.0540738  -0.129677
 -0.229416  -0.518326     0.0257288  …  -0.0898137   -0.0540738  -0.129677
 -0.229416   0.259748     0.0257288     -0.0898137   -0.0540738  -0.129677
 -0.229416   0.718977     0.0257288     -0.0898137   -0.0540738  -0.129677
 -0.229416   0.0972915   -0.18246       -0.00544195  -0.0540738   0.233959
 -0.229416  -0.0124051   -0.18246       -0.00544195  -0.0540738   0.233959
 -0.229416  -0.0210506   -0.18246    …  -0.00544195  -0.0540738   0.233959
 -0.229416  -0.031195    -0.18246       -0.00544195  -0.0540738   0.233959
 -0.229416   0.0167614   -0.116932      -0.254757    -0.0540738  -0.129677
 -

20-element Vector{Float64}:
 -18.999999999999996
   0.9999999999999993
   0.9999999999999993
   0.9999999999999996
   0.9999999999999997
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   0.9999999999999998
   0.9999999999999999
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.0000000000000002
   1.000000000000001
   1.0000000000000042

20×20 Matrix{Float64}:
 -0.223607   0.0104344     0.0153619    …   0.0816307    -0.0660245
 -0.223607   0.0104344     0.0153619        0.0816307    -0.0660245
 -0.223607   0.0104344     0.0153619        0.0816307    -0.0660245
 -0.223607   0.0104344     0.0153619        0.0816307    -0.0660245
 -0.223607  -0.054504     -0.0177331       -0.103773     -0.0660245
 -0.223607  -0.054504     -0.0177331    …  -0.103773     -0.0660245
 -0.223607  -0.054504     -0.0177331       -0.103773     -0.0660245
 -0.223607   0.918739     -0.0177331       -0.103773     -0.0660245
 -0.223607  -0.166452      0.883857        -0.103773     -0.0660245
 -0.223607  -0.16954      -0.202374        -0.103773     -0.0660245
 -0.223607  -0.0613372    -0.0996629    …  -0.103773     -0.0660245
 -0.223607   0.0184031     0.0101207       -0.103773     -0.0660245
 -0.223607  -0.235264     -0.334691        -0.103773     -0.0660245
 -0.223607  -0.169439     -0.222274        -0.103773     -0.0660245
 -0.223607  -0.0336107   